Projet_Bibliotheque/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Projet_Bibliotheque.Models;

namespace Projet_Bibliotheque.Controllers
{
    public class HomeController : Controller
    {
        private SkyBiblioEntities db = new SkyBiblioEntities();


        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Recherche(String searchBy, String searching)
        {


            if (searchBy == "Titre")
            {
                return View(db.Livres.Where(x => x.Titre.StartsWith(searching)).ToList());
            }
            else

            {
                return View(db.Livres.Where(x => x.Categorie == searching).ToList());

            }

        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Projet_Bibliotheque/Controllers/PretsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Projet_Bibliotheque.Models;

namespace Projet_Bibliotheque.Controllers
{
    public class PretsController : Controller
    {
        private SkyBiblioEntities db = new SkyBiblioEntities();

        // GET: Prets
        public ActionResult Index()
        {
            var prets = db.Prets.Include(p => p.Livres).Include(p => p.Membres);
            return View(prets.ToList());
        }

        // GET: Prets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prets prets = db.Prets.Find(id);
            if (prets == null)
            {
                return HttpNotFound();
            }
            return View(prets);
        }

        // GET: Prets/Create
        public ActionResult Create()
        {
            ViewBag.Id_Livres = new SelectList(db.Livres, "Id_Livres", "Titre");
            ViewBag.Id_Membres = new SelectList(db.Membres, "Id_Membres", "Nom");
            return View();
        }

        // POST: Prets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_Prets,Id_Livres,Id_Membres,date_de_Pret,date_de_retour")] Prets prets)
        {

            var rent = from a in db.Prets where a.Id_Membres == prets.Id_Membres select a;
            int count = rent.Count();



            
                Livres b = db.Livres.Find(prets.Id_Livres);
                if (ModelState.IsValid)
                {
                    if (count < 3)
                    {
                        if (b.Quantite <= 0)
                        {


                            ViewBag.error = "Le livres n'existe pas!";


                        }
                        else
                        {
                            db.Prets.Add(prets);
                            db.SaveChanges();


                            return RedirectToAction("Index");
                        }

                    }
                    else
                    {
                        ViewBag.ErrorMessage = "Vous n'avez pas le droit de plus de 3 livres";
                    }
                }
            

                ViewBag.Id_Livres = new SelectList(db.Livres, "Id_Livres", "Titre", prets.Id_Livres);
                ViewBag.Id_Membres = new SelectList(db.Membres, "Id_Membres", "Nom", prets.Id_Membres);
                return View(prets);
            
        }

        // GET: Prets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prets prets = db.Prets.Find(id);
            if (prets == null)
            {
                return HttpNotFound();
            }
            ViewBag.Id_Livres = new SelectList(db.Livres, "Id_Livres", "Titre", prets.Id_Livres);
            ViewBag.Id_Membres = new SelectList(db.Membres, "Id_Membres", "Nom", prets.Id_Membres);
            return View(prets);
        }

        // POST: Prets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_Prets,Id_Livres,Id_Membres,date_de_Pret,date_de_retour")] Prets prets)
        {
            if (ModelState.IsValid)
            {
                db.Entry(prets).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Id_Livres = new SelectList(db.Livres, "Id_Livres", "Titre", prets.Id_Livres);
            ViewBag.Id_Membres = new SelectList(db.Membres, "Id_Membres", "Nom", prets.Id_Membres);
            return View(prets);
        }

        // GET: Prets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prets prets = db.Prets.Find(id);
            if (prets == null)
            {
                return HttpNotFound();
            }
            return View(prets);
        }

        // POST: Prets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Prets prets = db.Prets.Find(id);
            db.Prets.Remove(prets);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Projet_Bibliotheque/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Projet_Bibliotheque.Models;

namespace Projet_Bibliotheque.Controllers
{
    public class ReservationsController : Controller
    {
        private SkyBiblioEntities db = new SkyBiblioEntities();

        // GET: Reservations
        public ActionResult Index()
        {
            var reservation = db.Reservation.Include(r => r.Livres).Include(r => r.Membres);
            return View(reservation.ToList());
        }

        // GET: Reservations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservation.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }

        // GET: Reservations/Create
        public ActionResult Create()
        {
            ViewBag.Id_Livres = new SelectList(db.Livres, "Id_Livres", "Titre");
            ViewBag.Id_Membres = new SelectList(db.Membres, "Id_Membres", "Nom");
            return View();
        }

        // POST: Reservations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_Reserv,Id_Livres,Id_Membres")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                db.Reservation.Add(reservation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Id_Livres = new SelectList(db.Livres, "Id_Livres", "Titre", reservation.Id_Livres);
            ViewBag.Id_Membres = new SelectList(db.Membres, "Id_Membres", "Nom", reservation.Id_Membres);
            return View(reservation);
        }

        // GET: Reservations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservation.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            ViewBag.Id_Livres = new SelectList(db.Livres, "Id_Livres", "Titre", reservation.Id_Livres);
            ViewBag.Id_Membres = new SelectList(db.Membres, "Id_Membres", "Nom", reservation.Id_Membres);
            return View(reservation);
        }

        // POST: Reservations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_Reserv,Id_Livres,Id_Membres")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reservation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Id_Livres = new SelectList(db.Livres, "Id_Livres", "Titre", reservation.Id_Livres);
            ViewBag.Id_Membres = new SelectList(db.Membres, "Id_Membres", "Nom", reservation.Id_Membres);
            return View(reservation);
        }

        // GET: Reservations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservation.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }

        // POST: Reservations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reservation reservation = db.Reservation.Find(id);
            db.Reservation.Remove(reservation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Projet_Bibliotheque/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Projet_Bibliotheque/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Projet_Bibliotheque/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h2 style="text-align:center">Quand livre et cerveau font bon ménage.</h2>
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <img src="~/Images/Livre_1.jpg" alt="Livre 1" style="width:100%; height:80%;">


            </div>

            <div class="item">
                <img src="~/Images/Livre_2.jpg" alt="Livre 2" style="width:100%;  height:80%;">

            </div>

            <div class="item">
                <img src="~/Images/Livre_3.jpg" alt="Livre 3" style="width:100%;  height:80%;">
            </div>
        </div>
    </div>
</div>

Projet_Bibliotheque/Views/Home/Recherche.cshtml
@model IEnumerable<Projet_Bibliotheque.Models.Livres>
@{
    ViewBag.Title = "Recherche";
}

<h2>Recherche</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Titre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Auteur)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categorie)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantite)
        </th>
        <th></th>
    </tr>

    @if (Model.Count() == 0)
    {
        <tr>
            <td colspan="4">Introuvabl</td>

        </tr>

    }
    else
    {
        foreach (var item in Model)
        {

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Titre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Auteur)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Categorie)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantite)
                </td>

            </tr>
        }
    }

</table>
<div id="reserver" >
    @using (Html.BeginForm("Create", "Reservations", FormMethod.Get))
    {
        <input type="submit" id="myBtn" value="Reserver" style="width:80px; background-color:antiquewhite"/>

    }
    <br />
    @using (Html.BeginForm("Create", "Prets", FormMethod.Get))
    {
        <input type="submit" id="myBtn" value="Prêter" style="width:80px; background-color:cyan"/>

    }

</div>